development:
  adapter: mysql
  database: pivotal_planning_poker_development
  username: pivotal_poker
  password: royalflush

test:
  adapter: mysql
  database: pivotal_planning_poker_test
  username: pivotal_poker
  password: royalflush
